name = "LeanBlockCourse26"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["LeanBlockCourse26"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
weak.linter.style.emptyLine = false
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.28.0"

[[lean_lib]]
name = "LeanBlockCourse26"
